// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzItcM2lRHsUN-n8zCTJZ5QcOzoQG1Kp4',
    appId: '1:100923170468:web:4525fefc7dd528b1895031',
    messagingSenderId: '100923170468',
    projectId: 'sorkar-agro',
    authDomain: 'sorkar-agro-48c87.firebaseapp.com',
    databaseURL: 'https://sorkar-agro-default-rtdb.firebaseio.com',
    storageBucket: 'sorkar-agro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXEzocuzBeyHbDH1GHRwFgwEaKYmHZsh4',
    appId: '1:100923170468:android:f3549aa2ba91fcc6895031',
    messagingSenderId: '100923170468',
    projectId: 'sorkar-agro',
    databaseURL: 'https://sorkar-agro-default-rtdb.firebaseio.com',
    storageBucket: 'sorkar-agro.firebasestorage.app',
  );
}
